export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const ROLE_LOADING = "ROLE_LOADING";
export const SET_CURRENT_ROLE = "SET_CURRENT_ROLE";

export const SUBMISSION_TYPE_LOADING = "SUBMISSION_TYPE_LOADING";
export const SET_CURRENT_SUBMISSION_TYPE = "SET_CURRENT_SUBMISSION_TYPE";

export const USER_ADD = "USER_ADD";
export const USER_UPDATE = "USER_UPDATE";

export const TOPIC_ADD = "TOPIC_ADD";
export const TOPIC_UPDATE = "TOPIC_UPDATE";

export const GROUP_ADD = "GROUP_ADD";
export const GROUP_UPDATE = "GROUP_UPDATE";

export const SUPERVISOR_ADD = "SUPERVISOR_ADD";
export const SUPERVISOR_UPDATE = "SUPERVISOR_UPDATE";

export const COSUPERVISOR_ADD = "COSUPERVISOR_ADD";
export const COSUPERVISOR_UPDATE = "COSUPERVISOR_UPDATE";

export const ROLE_ADD = "ROLE_ADD";
export const ROLE_UPDATE = "ROLE_UPDATE";

export const SUBMISSION_TYPE_ADD = "SUBMISSION_TYPE_ADD";
export const SUBMISSION_TYPE_UPDATE = "SUBMISSION_TYPE_UPDATE";
